---
title: Welcome To My Blog!
author: Katie Socolow
date: '2018-06-20'
slug: welcome-to-my-blog
categories: []
tags: []
output:
  html_document:
    font-size: 2.5em
    theme: journal
    highlight: espresso
---


# HELLO WORLD!
```{r setup, include=FALSE}
library(flexdashboard)
library(vcd)
library(magrittr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(plotly)
library(prettydoc)
library(rmarkdown)
```

My name is $\color{blue}{\text{Katie Socolow}}$ and I am a rising third year at the University of Virginia. I'm studying mathematical statistics and as a personal goal, I've decided to practice my newly acquired R programming skills by crafting a personal blog. So bear with me, I've got a long way to go and SO much to learn, but I'm going to make the best of it. 

I haven't quite decided yet what I want to make of this blog but my plan is to craft it along the way. Maybe it'll be mostly about food, as I'm probably the biggest foodie you'll ever meet. Maybe it'll be focused on sports analytics, my ideal career path (at the moment), and showcase all of my personal and coding exploration within the field. Maybe it will just be about how my day was and my take on the world. Who knows? Hopefully you'll stick with me and find out.

But before you make any decisions about your dedication to the words on your screen that have pretty much just flowed out filterless....you're probably wondering about me. Who am I? What a horrible question to be asked and to ask yourself. So broad, daunting and overwhelming. Yet so crucial to understand. SO.....here's a quick snapshot of my life.

## Childhood
I grew up in a small suburb to New York City called Chappaqua, NY. From Kindergarten until graduation, I was in classes with the same peers so we all knew everything about everyone. Considering there were 333 in my graduating class, that's pretty crazy to think about. I had mixed feelings about my hometown and my childhood while living there because of some bas experiences but ever since attending college, I have a new appreciation for the familiarity of it. Just a 55 minute train ride away from New York City, I am truly grateful that I had the opportunities to experience NYC as a local from a young age. It is truly the greatest city in the world and I love exploring it. Especialy.....(and this brings me to my next point) eating my way through it!

## FOOOOOOOD
I am an absolute food FANATIC! While some people eat to live, I live to eat. I plan entire days, even weeks, around my meals and love to try new foods, restaurants, trends, you name it. You can never run out of options, especially when you start to break into the specialty restuarants. You can find a restaurant for ANYTHING in the city, whether it be mac and cheese to gnocchi to cookie dough or avocados. Have a craving? I guarantee you that there is a little business in the city that serves up JUST what you're looking for. I have Celiac Disease which means that I have to eat gluten free [no wheat, rye, oats, barley or malt] but the city still throws me PLENTY of options. Some of my favorites include Senza Gluten in the East Village, Colors in Greenwich Village, Bistango in the Kimberly Hotel, S'Mac and The Sparrow Tavern in Astoria, Queens. Looking for some sweets? I'd recommend The Good Batch or Melt Bakery for Ice Cream Sandwiches or Dö for edible cookie dough! 



 