---
title: South African Updates
author: Katie Socolow
date: '2018-06-27'
slug: south-african-updates
categories: []
tags: []
output:
  html_document:
    font-size: 2.5em
    theme: journal
    highlight: espresso
---
## What am I up to?

I guess it's time to just casually put this out there but....I've been living in Cape Town, South Africa for the last 5 weeks! I'm studying abroad here on a program called iXperience. For the first four weeks, I took a class on Data Science and learned about programming in R and Python. I made linear regression models, decision trees, neural networks, and spent countless hours trying to rangle data. BUT I have definitely had ample time to do OTHER more INTERESTING thigns as well. SO now I'm going to use this as a recap tool for myself to remember all of the amazing experiences I've had while being here

### Here are some of the things I've been doing!
  + Hiking
    - I've hiked Lions Head, TWICE now! Being from New York, I'm not much of an outdoorsy person or a nature gal by ANY means but I did really enjoy hiking Lions Head. The first time I did a sunrise hike at 6:30am. The difficulty increased tremendously and although native cape tonians would argue that it's the "easiest" of the hikes, I would strongly disagree. That hike was BY NO MEANS easy but the view truly was spectacular. 
    _ I have yet to hike Table Mountain but I plan to do that in the near future. I'll keep y'all posted on how it goes.
  + Eating
    - I've truly been eating my way through this incredible city! I've eaten at The Test Kitchen, which is not only the 50th best restaurant in the world but the VERY best restaurant in all of Africa, not once but TWICE now. It was truly the best meal of my entire life and mid meal I had a life changing epiphany: I want to attent culinary school. Perhaps following graduation in 2020, perhaps after working as a data scientist, perhaps in 30 years from now. I had a moment of clarity while savoring the perfection of the edible creations, food is the truest, most pure passion that I have and I need to follow it. I truly believe that I will not be happy if I do not have food in my life. Some other incredible restaurants that I've been to include The Village Idiot, Cabrón Taco Bar, and Asoka. 
  + Safari
    - Last weekend my friends and I went on a Safari which explored the Garden Route in the Eastern Cape. It was an incredible weekend! We saw almost all of the big 5 [rhinos, lions, buffalo, leopard and elephants] as well as giraffes, cheetahs, springbok, elan and many others. It was such a cool experience to see these animals in their natural habitat and explore the South African country side more.
  + Surfing
    - One of my first weekends in Cape Town I was able to go surfing in the cute little surfing town of Muizenberg. It was so fun! 
  + Cape Point and Cape of Good Hope
    -
  + 
    
    
